site_name: Digital Garden

theme:
  features:
   - navigation.sections
    - navigation.expand
    - navigation.tracking
    - toc.integrate
    
  name: material
  palette:
    - scheme: slate
      primary: white
      accent: black

nav:
  - Home: index.md
  - Formula 1:
    - Intro: f1/index.md
    - 2025: f1/f1-2025.md
    - 2026: f1/f1-2026.md
  - Music:
    - An Album a Day: album/aad-2026.md
    - The Best: album/top.md
  - Games:
    - Dwarf Fortress:
      - Intro: gaming/df.md
      - Risenhames (Active): gaming/df-risenhames.md
      - DF plans: gaming/df-plans.md
    - Motor Town: gaming/mtown.md


