site_name: Digital Garden
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  name: material
  palette:
    - scheme: slate
      primary: white
      accent: black

nav:
  - Home: index.md
  - Formula 1:
    - 2025: f1/f1.md
  - Music:
    - An Album a Day: album/aad.md
    - The Best: album/top.md
  - Games: 
    - Dwarf Fortress: gaming/df.md
    - Motor Town: gaming/mtown.md


