site_name: Digital Garden
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  name: material
  palette:
    - scheme: slate
      primary: white
      accent: light grey

nav:
  - Home: index.md
  - Music:
    - Album a Day: album/aad.md
    - Best Ever: album/top.md
  - Games: 
    - DF: gaming/df.md


