site_name: My Life Notes
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  name: material
  palette:
    - scheme: default
      primary: grey
      accent: black

nav:
  - Home: index.md
  - Games: 
    - Journal: gaming/df.md


