site_name: Digital Garden

theme:
  features:
   - navigation.sections
   - navigation.expand
   - navigation.tracking
   - toc.integrate
    
  name: github
  palette:
    - scheme: slate
      primary: black
      accent: black
      
  highlightjs: true
  hljs_style: github    

nav:
  - Home: index.md
  - Formula 1:
    - Intro: f1/index.md
    - 2025: f1/f1-2025.md
    - 2026: f1/f1-2026.md
  - Music:
    - An Album a Day: album/aad-2026.md
    - The Best: album/top.md
  - Games:
    - Intro: gaming/index.md
    - DF Risenhames (Active): gaming/df-risenhames.md
    - DF (inactive):

    - Motor Town: gaming/mtown.md


